language: minimal
dist: xenial

env:
  global:
    - REPO=stdswift/build
  matrix:
    - SWIFT=5.0.0 OS=trusty
    - SWIFT=5.0.0 OS=xenial
    - SWIFT=5.0.0 OS=bionic
    - SWIFT=5.0.1 OS=trusty
    - SWIFT=5.0.1 OS=xenial
    - SWIFT=5.0.1 OS=bionic
    - SWIFT=5.0.2 OS=trusty
    - SWIFT=5.0.2 OS=xenial
    - SWIFT=5.0.2 OS=bionic
    - SWIFT=5.0.3 OS=trusty
    - SWIFT=5.0.3 OS=xenial
    - SWIFT=5.0.3 OS=bionic
    - SWIFT=5.1.0 OS=trusty
    - SWIFT=5.1.0 OS=xenial
    - SWIFT=5.1.0 OS=bionic
    - SWIFT=5.1.1 OS=trusty
    - SWIFT=5.1.1 OS=xenial
    - SWIFT=5.1.1 OS=bionic
    - SWIFT=5.1.2 OS=trusty
    - SWIFT=5.1.2 OS=xenial
    - SWIFT=5.1.2 OS=bionic
    - SWIFT=5.1.3 OS=trusty
    - SWIFT=5.1.3 OS=xenial
    - SWIFT=5.1.3 OS=bionic
    - SWIFT=5.1.4 OS=trusty
    - SWIFT=5.1.4 OS=xenial
    - SWIFT=5.1.4 OS=bionic
    - SWIFT=5.1.5 OS=trusty
    - SWIFT=5.1.5 OS=xenial
    - SWIFT=5.1.5 OS=bionic
    - SWIFT=5.2.0 OS=xenial
    - SWIFT=5.2.0 OS=bionic
    - SWIFT=5.2.1 OS=xenial
    - SWIFT=5.2.1 OS=bionic
    - SWIFT=5.2.2 OS=xenial
    - SWIFT=5.2.2 OS=bionic
    - SWIFT=5.2.3 OS=xenial
    - SWIFT=5.2.3 OS=bionic
    - SWIFT=5.2.4 OS=xenial
    - SWIFT=5.2.4 OS=bionic
    - SWIFT=5.2.4 OS=focal

matrix:
  include:
    - os: osx
      env:
      osx_image: xcode10.2
    - os: osx
      env:
      osx_image: xcode10.3
    - os: osx
      env:
      osx_image: xcode11.5
    - os: osx
      env:
      osx_image: xcode11.6
    - os: osx
      env:
      osx_image: xcode12

install:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      docker pull $REPO:$OS-$SWIFT
    fi

script:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      docker run --volume `pwd`:/code --workdir /code $REPO:$OS-$SWIFT swift test
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      swift test --generate-linuxmain && git diff --exit-code
      swift test --enable-code-coverage
    fi

after_success:
  - |
    set -e
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      profile=.build/debug/codecov/default.profdata
      executable=.build/debug/${PWD##*/}PackageTests.xctest/Contents/MacOS/${PWD##*/}PackageTests
      coverage=.build/debug/codecov/${PWD##*/}.coverage.txt
      xcrun llvm-cov show -instr-profile $profile $executable > $coverage
      bash <(curl -s https://codecov.io/bash) -f $coverage
    fi
